# Generated by Django 4.0.2 on 2022-04-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(default='default.png', upload_to='thumbnail/')),
            ],
        ),
    ]
